import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { Users } from 'lucide-react';

// Helper to convert Google Drive View URLs to Direct URLs
const formatGoogleDriveUrl = (url) => {
    if (!url) return '';
    if (typeof url !== 'string') return '';

    // Robust ID extraction using Regex
    const idMatch = url.match(/\/d\/([a-zA-Z0-9_-]+)/) || url.match(/id=([a-zA-Z0-9_-]+)/);

    if (idMatch && idMatch[1]) {
        // Use the thumbnail endpoint which is often more reliable for images than 'uc'
        return `https://drive.google.com/thumbnail?id=${idMatch[1]}&sz=w1000`;
    }

    return url;
};

// Sub-component for robust image handling in cells
const ImageCell = ({ value, alt }) => {
    const [imgError, setImgError] = React.useState(false);
    const formattedUrl = formatGoogleDriveUrl(value);

    if (imgError || !formattedUrl) {
        return (
            <div className="w-10 h-10 rounded-lg bg-gray-100 border border-gray-200 flex items-center justify-center text-gray-400 font-bold text-xs">
                {alt ? alt.charAt(0).toUpperCase() : '?'}
            </div>
        );
    }

    return (
        <div className="w-10 h-10 rounded-lg overflow-hidden border border-gray-200 bg-white hover:border-pucho-purple transition-colors">
            <img
                src={formattedUrl}
                alt={alt}
                className="w-full h-full object-contain"
                onError={() => setImgError(true)}
            />
        </div>
    );
};

const CardsGrid = () => {
    const [shopCount, setShopCount] = useState(null);
    const [shops, setShops] = useState([]);
    const [columns, setColumns] = useState([]);
    const [loadingCount, setLoadingCount] = useState(true);

    const [searchTerm, setSearchTerm] = useState('');
    const [selectedImage, setSelectedImage] = useState(null); // State for modal

    useEffect(() => {
        let cleanupScript = null;
        let activeCallbackName = null;

        const fetchSheetData = () => {
            // Using the correct sheet ID provided by user
            const SHEET_ID = '1UcRAbcxmDkpiaFY7SWmc--79BJRvaRG1J6omsrj-8bg';
            const callbackName = 'googleSheetCountCallback_' + Math.floor(Math.random() * 100000);
            activeCallbackName = callbackName;

            window[callbackName] = (json) => {
                try {
                    if (json && json.table && json.table.rows) {
                        const rows = json.table.rows;

                        // Calculate active shop count (rows contains only data now)
                        const count = rows.length;
                        setShopCount(count);

                        // Parse Data for List
                        if (rows.length > 0) {
                            let headers = [];
                            let startRowIndex = 0;

                            // Strategy: Use API's native header parsing (most robust for mixed types)
                            if (json.table.cols) {
                                // 1. Identify all headers from API metadata
                                const allHeaders = json.table.cols.map((col, i) => {
                                    const val = col?.label?.trim();
                                    let name = val || `Column ${i + 1}`;
                                    // Store both name and index strictly
                                    return { name, index: i, isAutoGenerated: !val };
                                });

                                startRowIndex = 0; // Data starts immediately

                                // 2. Check which columns actually have data
                                const activeIndices = new Set();
                                for (let i = startRowIndex; i < rows.length; i++) {
                                    const row = rows[i];
                                    if (!row.c) continue;
                                    row.c.forEach((cell, colIndex) => {
                                        if (cell?.v !== undefined && cell?.v !== null && cell?.v !== '') {
                                            activeIndices.add(colIndex);
                                        }
                                    });
                                }

                                // 3. Filter headers: Keep if it has a real name OR if it has data
                                // This is fully dynamic: it shows what is in the sheet (or purely computed fallbacks for data columns)
                                const validHeaders = allHeaders.filter(h =>
                                    !h.name.startsWith('Column ') || activeIndices.has(h.index)
                                );

                                // Set Columns State with FULL objects {name, index}
                                setColumns(validHeaders);

                                // 4. Map rows to objects using indices as keys for absolute stability
                                const parsedShops = [];
                                for (let i = startRowIndex; i < rows.length; i++) {
                                    const row = rows[i];
                                    if (!row.c) continue;

                                    const shopValues = {};
                                    // We fetch data based on the VALID INDICES defined in validHeaders
                                    validHeaders.forEach(({ index }) => {
                                        const cell = row.c[index];
                                        // Store by Index to avoid key collisions
                                        shopValues[index] = cell?.v ?? '';
                                    });
                                    parsedShops.push(shopValues);
                                }
                                setShops(parsedShops);
                            }
                        }
                    }
                } catch (error) {
                    console.error('Error fetching sheets:', error);
                } finally {
                    setLoadingCount(false);
                    // Only delete if it's the specific callback for this request
                    delete window[callbackName];
                }
            };

            const script = document.createElement('script');
            // Added &headers=0 to force the first row to be treated as data
            script.src = `https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=responseHandler:${callbackName}`;
            script.onerror = () => {
                setLoadingCount(false);
                delete window[callbackName];
            };
            document.body.appendChild(script);
            cleanupScript = script;
        };

        fetchSheetData();

        return () => {
            if (cleanupScript) cleanupScript.remove();
            // Prevent ReferenceError by making the callback a no-op instead of deleting it immediately
            // The script context might still try to call it if it loads after unmount
            if (activeCallbackName) {
                window[activeCallbackName] = () => { };
            }
        };
    }, []);

    const filteredShops = shops.filter(shop => {
        if (!searchTerm) return true;
        const lowerTerm = searchTerm.toLowerCase();
        return Object.values(shop).some(val =>
            String(val).toLowerCase().includes(lowerTerm)
        );
    });

    return (
        <div className="space-y-8">
            {/* Top Stats Section */}
            <div className="">
                <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 max-w-sm">
                    <div className="flex items-center gap-4">
                        <div className="w-12 h-12 rounded-full bg-pucho-purple/10 flex items-center justify-center text-pucho-purple">
                            <Users size={24} />
                        </div>
                        <div>
                            <p className="text-sm font-medium text-gray-500">Total Active Shops</p>
                            <h3 className="text-2xl font-bold text-gray-900">
                                {loadingCount ? (
                                    <span className="animate-pulse">...</span>
                                ) : (
                                    shopCount !== null ? shopCount : '-'
                                )}
                            </h3>
                        </div>
                    </div>
                </div>
            </div>

            {/* Shop List Section */}
            <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="px-6 py-4 border-b border-gray-100 flex items-center justify-between gap-4">
                    <h3 className="text-lg font-bold text-gray-900">Registered Shops</h3>

                    {/* Search Input */}
                    <div className="relative">
                        <input
                            type="text"
                            placeholder="Search..."
                            value={searchTerm}
                            onChange={(e) => setSearchTerm(e.target.value)}
                            className="pl-10 pr-4 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-pucho-purple/20 focus:border-pucho-purple w-64 transition-all"
                        />
                        <svg className="w-4 h-4 text-gray-400 absolute left-3 top-1/2 -translate-y-1/2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                        </svg>
                    </div>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full text-left border-collapse">
                        <thead>
                            <tr className="bg-gray-50/50 border-b border-gray-100">
                                {/* Dynamically render headers from state */}
                                {columns.length > 0 && columns.map((col, idx) => (
                                    <th key={idx} className="px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">
                                        {col.name}
                                    </th>
                                ))}
                                {columns.length === 0 && !loadingCount && (
                                    <th className="px-6 py-3 text-xs font-semibold text-gray-500 uppercase tracking-wider">Status</th>
                                )}
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                            {loadingCount ? (
                                <tr>
                                    <td colSpan={Math.max(1, columns.length)} className="px-6 py-8 text-center text-gray-500">
                                        <div className="flex items-center justify-center gap-2">
                                            <div className="w-4 h-4 border-2 border-pucho-purple border-t-transparent rounded-full animate-spin"></div>
                                            Loading shops data...
                                        </div>
                                    </td>
                                </tr>
                            ) : filteredShops.length > 0 ? (
                                filteredShops.map((shop, rowIndex) => (
                                    <tr key={rowIndex} className="hover:bg-gray-50/50 transition-colors">
                                        {columns.map((col, colIndex) => {
                                            const value = shop[col.index] || ''; // Strict Index lookup

                                            // Formatting checks based on header name
                                            const headerLower = col.name.toLowerCase();
                                            const isImage = headerLower.includes('logo') || headerLower.includes('image') || (headerLower.includes('qr') && headerLower.includes('url'));

                                            // Robust URL check: allow direct links without protocol if they look like domains
                                            let finalValue = value;
                                            if (typeof value === 'string' && !value.startsWith('http') && !value.startsWith('//') && (value.includes('.') || value.includes('localhost'))) {
                                                finalValue = `https://${value}`;
                                            }

                                            const isUrl = typeof finalValue === 'string' && (finalValue.startsWith('http') || finalValue.startsWith('//'));

                                            // Dynamic Alt Text: Try to find Shop Name for better fallback
                                            const shopNameIndex = columns.find(c => c.name.toLowerCase().includes('shop name'))?.index;
                                            const shopName = shopNameIndex !== undefined ? shop[shopNameIndex] : '';
                                            const dynamicAlt = shopName || col.name;

                                            return (
                                                <td key={colIndex} className="px-6 py-4 text-sm text-gray-700 whitespace-nowrap">
                                                    {isImage && isUrl ? (
                                                        <div
                                                            onClick={() => setSelectedImage(finalValue)}
                                                            className="block w-10 h-10 cursor-pointer transition-transform hover:scale-110 active:scale-95"
                                                            title={`Click to view ${col.name}`}
                                                        >
                                                            <ImageCell value={finalValue} alt={dynamicAlt} />
                                                        </div>
                                                    ) : isUrl ? (
                                                        <a href={finalValue} target="_blank" rel="noreferrer" className="text-pucho-purple hover:underline flex items-center gap-1 max-w-[150px] truncate">
                                                            Link <span className="text-xs">↗</span>
                                                        </a>
                                                    ) : (
                                                        <span className="max-w-[200px] block truncate" title={value}>
                                                            {value}
                                                        </span>
                                                    )}
                                                </td>
                                            );
                                        })}
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan={Math.max(1, columns.length)} className="px-6 py-8 text-center text-gray-500">
                                        {searchTerm ? 'No matching shops found.' : 'No shops found.'}
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Image Preview Modal - Portaled to Body to avoid Z-index issues with Header */}
            {selectedImage && createPortal(
                <div
                    className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm animate-fade-in p-4"
                    onClick={() => setSelectedImage(null)}
                >
                    <div className="relative max-w-3xl max-h-[90vh] bg-white rounded-2xl shadow-xl overflow-hidden p-2" onClick={e => e.stopPropagation()}>
                        <button
                            className="absolute top-4 right-4 bg-white/10 hover:bg-white/20 text-white rounded-full p-2 transition-colors z-10"
                            onClick={() => setSelectedImage(null)}
                        >
                            <svg className="w-6 h-6 text-gray-800 drop-shadow-md" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                        </button>
                        <img
                            src={formatGoogleDriveUrl(selectedImage)}
                            alt="Full View"
                            className="w-full h-full object-contain max-h-[85vh] rounded-lg bg-gray-50"
                        />
                    </div>
                </div>,
                document.body
            )}
        </div>
    );
};

export default CardsGrid;
